/* GENERATED by scripts/build-tokens.mjs — do not edit.
   Edit src/styles/brand.mjs and run `npm run build:tokens`. */

export type WebvuToken =
  | '--wv-accent'
  | '--wv-accent-contrast'
  | '--wv-accent-hover'
  | '--wv-accent-subtle'
  | '--wv-action'
  | '--wv-action-active'
  | '--wv-action-hover'
  | '--wv-action-subtle'
  | '--wv-action-text'
  | '--wv-border'
  | '--wv-border-strong'
  | '--wv-brand'
  | '--wv-brand-active'
  | '--wv-brand-contrast'
  | '--wv-brand-hover'
  | '--wv-brand-subtle'
  | '--wv-danger'
  | '--wv-danger-subtle'
  | '--wv-duration-base'
  | '--wv-duration-fast'
  | '--wv-duration-slow'
  | '--wv-ease'
  | '--wv-focus-ring'
  | '--wv-font-display'
  | '--wv-font-sans'
  | '--wv-info'
  | '--wv-info-subtle'
  | '--wv-neutral-100'
  | '--wv-neutral-200'
  | '--wv-neutral-300'
  | '--wv-neutral-400'
  | '--wv-neutral-50'
  | '--wv-neutral-500'
  | '--wv-neutral-600'
  | '--wv-neutral-700'
  | '--wv-neutral-800'
  | '--wv-neutral-900'
  | '--wv-radius-full'
  | '--wv-radius-lg'
  | '--wv-radius-md'
  | '--wv-radius-sm'
  | '--wv-shadow-lg'
  | '--wv-shadow-md'
  | '--wv-shadow-sm'
  | '--wv-space-1'
  | '--wv-space-12'
  | '--wv-space-16'
  | '--wv-space-2'
  | '--wv-space-24'
  | '--wv-space-3'
  | '--wv-space-4'
  | '--wv-space-6'
  | '--wv-space-8'
  | '--wv-success'
  | '--wv-success-subtle'
  | '--wv-surface'
  | '--wv-surface-admin'
  | '--wv-surface-inverse'
  | '--wv-surface-raised'
  | '--wv-surface-sunken'
  | '--wv-text'
  | '--wv-text-2xl'
  | '--wv-text-3xl'
  | '--wv-text-4xl'
  | '--wv-text-5xl'
  | '--wv-text-base'
  | '--wv-text-inverse'
  | '--wv-text-lg'
  | '--wv-text-muted'
  | '--wv-text-on-brand'
  | '--wv-text-sm'
  | '--wv-text-subtle'
  | '--wv-text-xl'
  | '--wv-text-xs'
  | '--wv-warning'
  | '--wv-warning-subtle';

export const WEBVU_TOKENS: readonly WebvuToken[] = [
  '--wv-accent',
  '--wv-accent-contrast',
  '--wv-accent-hover',
  '--wv-accent-subtle',
  '--wv-action',
  '--wv-action-active',
  '--wv-action-hover',
  '--wv-action-subtle',
  '--wv-action-text',
  '--wv-border',
  '--wv-border-strong',
  '--wv-brand',
  '--wv-brand-active',
  '--wv-brand-contrast',
  '--wv-brand-hover',
  '--wv-brand-subtle',
  '--wv-danger',
  '--wv-danger-subtle',
  '--wv-duration-base',
  '--wv-duration-fast',
  '--wv-duration-slow',
  '--wv-ease',
  '--wv-focus-ring',
  '--wv-font-display',
  '--wv-font-sans',
  '--wv-info',
  '--wv-info-subtle',
  '--wv-neutral-100',
  '--wv-neutral-200',
  '--wv-neutral-300',
  '--wv-neutral-400',
  '--wv-neutral-50',
  '--wv-neutral-500',
  '--wv-neutral-600',
  '--wv-neutral-700',
  '--wv-neutral-800',
  '--wv-neutral-900',
  '--wv-radius-full',
  '--wv-radius-lg',
  '--wv-radius-md',
  '--wv-radius-sm',
  '--wv-shadow-lg',
  '--wv-shadow-md',
  '--wv-shadow-sm',
  '--wv-space-1',
  '--wv-space-12',
  '--wv-space-16',
  '--wv-space-2',
  '--wv-space-24',
  '--wv-space-3',
  '--wv-space-4',
  '--wv-space-6',
  '--wv-space-8',
  '--wv-success',
  '--wv-success-subtle',
  '--wv-surface',
  '--wv-surface-admin',
  '--wv-surface-inverse',
  '--wv-surface-raised',
  '--wv-surface-sunken',
  '--wv-text',
  '--wv-text-2xl',
  '--wv-text-3xl',
  '--wv-text-4xl',
  '--wv-text-5xl',
  '--wv-text-base',
  '--wv-text-inverse',
  '--wv-text-lg',
  '--wv-text-muted',
  '--wv-text-on-brand',
  '--wv-text-sm',
  '--wv-text-subtle',
  '--wv-text-xl',
  '--wv-text-xs',
  '--wv-warning',
  '--wv-warning-subtle',
];
