#!/usr/bin/env node
/**
 * Generates primitives.css and tokens.d.ts from brand.mjs.
 *
 * SPEC.md § Webvu Design System — a rebrand edits brand.mjs and runs this;
 * no component file should appear in the resulting diff.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import * as brand from '../src/styles/brand.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const stylesDir = join(here, '..', 'src', 'styles');

const BANNER = `/* GENERATED by scripts/build-tokens.mjs — do not edit.\n   Edit src/styles/brand.mjs and run \`npm run build:tokens\`. */\n`;

/** Colour groups become hsl() values; everything else is emitted verbatim. */
const colourGroups = {
  brand: brand.brand,
  accent: brand.accent,
  neutral: brand.neutral,
  '': brand.status,
};

const rawGroups = {
  radius: brand.radius,
  space: brand.space,
  text: brand.fontSize,
  font: brand.font,
  shadow: brand.shadow,
  '': brand.motion,
};

const names = [];
const lines = [];

function emit(name, value) {
  names.push(name);
  lines.push(`  ${name}: ${value};`);
}

for (const [group, values] of Object.entries(colourGroups)) {
  for (const [key, triple] of Object.entries(values)) {
    const suffix = key === 'DEFAULT' ? '' : `-${key}`;
    const base = group ? `--wv-${group}` : '--wv';
    emit(`${base}${suffix}`, `hsl(${triple})`);
  }
}

for (const [group, values] of Object.entries(rawGroups)) {
  for (const [key, value] of Object.entries(values)) {
    const base = group ? `--wv-${group}` : '--wv';
    emit(`${base}-${key}`, value);
  }
}

writeFileSync(
  join(stylesDir, 'primitives.css'),
  `${BANNER}\n:root {\n${lines.join('\n')}\n}\n`,
  'utf8',
);

/**
 * The semantic layer is hand-written, so its names are listed here too —
 * the lint rule checks every --wv-* used in src/ against this union.
 */
const semanticNames = [
  '--wv-surface', '--wv-surface-raised', '--wv-surface-sunken',
  '--wv-surface-inverse', '--wv-surface-admin',
  '--wv-text', '--wv-text-muted', '--wv-text-subtle', '--wv-text-inverse',
  '--wv-text-on-brand',
  '--wv-action', '--wv-action-hover', '--wv-action-active',
  '--wv-action-subtle', '--wv-action-text', '--wv-focus-ring',
  '--wv-border', '--wv-border-strong',
];

const all = [...new Set([...names, ...semanticNames])].sort();

writeFileSync(
  join(stylesDir, 'tokens.d.ts'),
  `${BANNER}\nexport type WebvuToken =\n${all.map((n) => `  | '${n}'`).join('\n')};\n\nexport const WEBVU_TOKENS: readonly WebvuToken[] = [\n${all
    .map((n) => `  '${n}',`)
    .join('\n')}\n];\n`,
  'utf8',
);

console.log(`tokens: ${names.length} primitives, ${all.length} total names`);
